/* gui_journey.c - Journey Visualizer with Constraint Analysis */
const char *JOURNEY_HTML =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>B&B Journey Visualizer</title>\n"
"<link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n"
"<link rel=\"icon\" href=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=\">\n"
"<style>\n"
":root{--bg:hsl(201,100%,13%);--fg:#fff;--muted:#94a3b8;--green:#4ade80;--red:#f87171;--orange:#fb923c;--blue:#38bdf8;--yellow:#fcd34d;--panel:rgba(10,18,35,0.82);--border:rgba(255,255,255,0.1);}\n"
"*{margin:0;padding:0;box-sizing:border-box;}\n"
"body{font-family:\"Inter\",sans-serif;background:var(--bg);color:var(--fg);height:100vh;overflow:hidden;display:flex;flex-direction:column;}\n"
"#loader{position:fixed;inset:0;background:var(--bg);display:flex;flex-direction:column;align-items:center;justify-content:center;z-index:999;gap:16px;}\n"
".spin{width:44px;height:44px;border:4px solid rgba(56,189,248,0.15);border-top-color:#38bdf8;border-radius:50%;animation:spin .8s linear infinite;}\n"
"@keyframes spin{to{transform:rotate(360deg);}}\n"
"header{position:relative;z-index:10;padding:10px 20px;background:rgba(10,18,35,0.75);backdrop-filter:blur(12px);border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;flex-shrink:0;gap:10px;}\n"
"header h1{font-size:.95rem;font-weight:700;white-space:nowrap;}\n"
"header h1 span{color:#38bdf8;font-weight:400;font-size:.8rem;margin-left:6px;}\n"
".stat-row{display:flex;gap:6px;flex-wrap:wrap;}\n"
".stat-pill{background:rgba(255,255,255,.06);border:1px solid var(--border);border-radius:9999px;padding:4px 11px;font-size:.72rem;color:var(--muted);}\n"
".stat-pill strong{color:var(--fg);}\n"
"header button{background:rgba(255,255,255,.06);border:1px solid var(--border);color:var(--fg);padding:5px 12px;border-radius:9999px;font-size:.75rem;cursor:pointer;transition:background .2s;}\n"
"header button:hover{background:rgba(255,255,255,.14);}\n"
".main{position:relative;z-index:5;flex:1;overflow:hidden;display:flex;}\n"
".road-panel{width:220px;flex-shrink:0;display:flex;flex-direction:column;border-right:1px solid var(--border);background:rgba(8,14,28,.6);backdrop-filter:blur(8px);}\n"
".road-label{font-size:.62rem;font-weight:700;text-transform:uppercase;letter-spacing:1.5px;color:var(--muted);padding:12px 12px 6px;}\n"
".road-scroll{flex:1;overflow-y:auto;padding:0 8px 12px;}\n"
".road-scroll::-webkit-scrollbar{width:3px;}\n"
".road-scroll::-webkit-scrollbar-thumb{background:rgba(255,255,255,.1);border-radius:2px;}\n"
".road-step{position:relative;padding:0 0 0 26px;cursor:pointer;margin-bottom:2px;}\n"
".road-step::before{content:\"\";position:absolute;left:8px;top:20px;width:2px;height:calc(100% + 2px);background:rgba(255,255,255,.08);}\n"
".road-step:last-child::before{display:none;}\n"
".road-dot{position:absolute;left:0;top:5px;width:18px;height:18px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:8px;font-weight:700;border:2px solid rgba(255,255,255,.15);z-index:1;transition:transform .1s;}\n"
".road-step:hover .road-dot{transform:scale(1.25);}\n"
".road-card{background:rgba(255,255,255,.025);border:1px solid rgba(255,255,255,.05);border-radius:7px;padding:5px 7px;font-size:.67rem;line-height:1.35;transition:background .1s;}\n"
".road-step.active .road-card{background:rgba(56,189,248,.1);border-color:rgba(56,189,248,.35);}\n"
".road-step.active .road-dot{border-color:#38bdf8;box-shadow:0 0 7px #38bdf8;}\n"
".step-type-lbl{font-size:.58rem;font-weight:700;text-transform:uppercase;letter-spacing:.5px;margin-bottom:1px;}\n"
".grid-area{flex:1;display:flex;align-items:center;justify-content:center;padding:14px;gap:16px;overflow:hidden;}\n"
".sudoku-wrap{display:flex;flex-direction:column;align-items:center;gap:8px;}\n"
".sudoku-grid{display:grid;grid-template-columns:repeat(9,1fr);gap:0;border:2.5px solid rgba(255,255,255,.38);border-radius:8px;overflow:hidden;flex-shrink:0;}\n"
".sc{width:50px;height:50px;display:flex;align-items:center;justify-content:center;font-size:1.2rem;font-weight:600;border:1px solid rgba(255,255,255,.07);transition:background .18s,color .18s;position:relative;}\n"
".sc.hl-block{background:rgba(255,255,255,.04);}\n"
".sc.br{border-right:2.5px solid rgba(255,255,255,.32);}\n"
".sc.bb{border-bottom:2.5px solid rgba(255,255,255,.32);}\n"
".sc.fixed{color:#e2e8f0;font-weight:700;}\n"
".sc.placed{color:#38bdf8;font-weight:600;}\n"
".sc.active-c{background:rgba(56,189,248,.25);color:#38bdf8;font-weight:800;box-shadow:inset 0 0 0 2px #38bdf8;}\n"
".sc.bt-c{background:rgba(248,113,113,.2);color:#f87171;}\n"
".sc.pr-c{background:rgba(251,146,60,.2);color:#fb923c;}\n"
".sc.empty{color:rgba(255,255,255,.12);}\n"
".sc.row-hl{background:rgba(56,189,248,.06);}\n"
".sc.col-hl{background:rgba(56,189,248,.06);}\n"
".sc.block-hl{background:rgba(252,211,77,.07);}\n"
".grid-caption{font-size:.68rem;color:var(--muted);text-align:center;}\n"
".info-panel{width:320px;flex-shrink:0;overflow-y:auto;padding:12px;display:flex;flex-direction:column;gap:10px;height:100%;align-self:stretch;}\n"
".info-panel::-webkit-scrollbar{width:3px;}\n"
".info-panel::-webkit-scrollbar-thumb{background:rgba(255,255,255,.1);}\n"
".icard{background:var(--panel);border:1px solid var(--border);border-radius:11px;padding:12px;}\n"
".icard h3{font-size:.65rem;font-weight:700;text-transform:uppercase;letter-spacing:1.5px;color:var(--muted);margin-bottom:9px;}\n"
".irow{display:flex;justify-content:space-between;align-items:center;padding:3px 0;font-size:.77rem;border-bottom:1px solid rgba(255,255,255,.04);}\n"
".irow:last-child{border:none;}\n"
".irow .lbl{color:var(--muted);}\n"
".irow .val{font-weight:600;}\n"
".constraint-block{margin-bottom:8px;padding:8px;border-radius:8px;font-size:.74rem;line-height:1.5;}\n"
".constraint-block.row-c{background:rgba(56,189,248,.06);border:1px solid rgba(56,189,248,.15);}\n"
".constraint-block.col-c{background:rgba(74,222,128,.06);border:1px solid rgba(74,222,128,.15);}\n"
".constraint-block.blk-c{background:rgba(252,211,77,.06);border:1px solid rgba(252,211,77,.15);}\n"
".constraint-block.result-c{background:rgba(56,189,248,.1);border:1px solid rgba(56,189,248,.3);}\n"
".constraint-block.prune-c{background:rgba(251,146,60,.08);border:1px solid rgba(251,146,60,.25);}\n"
".constraint-block.bt-c2{background:rgba(248,113,113,.08);border:1px solid rgba(248,113,113,.25);}\n"
".cbl-title{font-weight:700;margin-bottom:3px;}\n"
".digit-pill{display:inline-flex;align-items:center;justify-content:center;width:20px;height:20px;border-radius:4px;font-size:.72rem;font-weight:700;margin:1px;}\n"
".dp-elim{background:rgba(248,113,113,.25);color:#f87171;text-decoration:line-through;}\n"
".dp-ok{background:rgba(74,222,128,.25);color:#4ade80;}\n"
".dp-chosen{background:#38bdf8;color:#060b13;}\n"
"controls{position:relative;z-index:10;display:flex;align-items:center;justify-content:center;gap:10px;padding:10px 20px;background:rgba(10,18,35,.75);backdrop-filter:blur(12px);border-top:1px solid var(--border);flex-shrink:0;flex-wrap:wrap;}\n"
".cb{background:rgba(255,255,255,.06);border:1px solid var(--border);color:var(--fg);padding:7px 15px;border-radius:9999px;font-size:.8rem;font-weight:500;cursor:pointer;transition:background .15s,transform .1s;font-family:inherit;}\n"
".cb:hover{background:rgba(255,255,255,.12);transform:scale(1.02);}\n"
".cb:active{transform:scale(.97);}\n"
".cb.primary{background:#38bdf8;color:#060b13;border:none;font-weight:700;}\n"
".cb.primary:hover{background:#7dd3fc;}\n"
".prog-wrap{flex:1;max-width:260px;}\n"
".prog-track{width:100%;height:4px;background:rgba(255,255,255,.08);border-radius:2px;overflow:hidden;}\n"
".prog-fill{height:100%;background:linear-gradient(90deg,#38bdf8,#4ade80);border-radius:2px;transition:width .1s;}\n"
".step-ctr{font-size:.72rem;color:var(--muted);margin-top:3px;text-align:center;}\n"
".legend{display:flex;gap:10px;flex-wrap:wrap;align-items:center;font-size:.68rem;color:var(--muted);}\n"
".li{display:flex;align-items:center;gap:4px;}\n"
".ld{width:9px;height:9px;border-radius:50%;}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div id=\"loader\"><div class=\"spin\"></div><div style=\"font-size:.9rem;font-weight:600;\">Solving &amp; Building Journey...</div><div style=\"font-size:.72rem;color:#94a3b8;\">Branch &amp; Bound exploring the state space</div></div>\n"
"<header>\n"
"  <h1>Branch &amp; Bound <span>Journey Visualizer</span></h1>\n"
"  <div class=\"stat-row\" id=\"hStats\"></div>\n"
"  <button onclick=\"goBack()\">&larr; Back to Solver</button>\n"
"</header>\n"
"<div class=\"main\">\n"
"  <div class=\"road-panel\">\n"
"    <div class=\"road-label\">Journey Road</div>\n"
"    <div class=\"road-scroll\" id=\"roadScroll\"><div id=\"roadInner\"></div></div>\n"
"  </div>\n"
"  <div class=\"grid-area\">\n"
"    <div class=\"sudoku-wrap\">\n"
"      <div class=\"sudoku-grid\" id=\"sGrid\"></div>\n"
"      <div class=\"grid-caption\" id=\"gridCaption\">Initial Puzzle</div>\n"
"    </div>\n"
"    <div class=\"info-panel\" id=\"iPanel\"></div>\n"
"  </div>\n"
"</div>\n"
"<div id=\"ctrlBar\" style=\"position:relative;z-index:10;display:flex;align-items:center;justify-content:center;gap:10px;padding:10px 20px;background:rgba(10,18,35,.75);backdrop-filter:blur(12px);border-top:1px solid rgba(255,255,255,0.1);flex-shrink:0;flex-wrap:wrap;\">\n"
"  <div class=\"legend\">\n"
"    <div class=\"li\"><div class=\"ld\" style=\"background:#38bdf8\"></div>Placed</div>\n"
"    <div class=\"li\"><div class=\"ld\" style=\"background:#f87171\"></div>Backtrack</div>\n"
"    <div class=\"li\"><div class=\"ld\" style=\"background:#fb923c\"></div>Pruned</div>\n"
"    <div class=\"li\"><div class=\"ld\" style=\"background:rgba(252,211,77,.4)\"></div>Active Block</div>\n"
"  </div>\n"
"  <button class=\"cb\" onclick=\"goTo(0)\">First</button>\n"
"  <button class=\"cb\" onclick=\"prev()\">Prev</button>\n"
"  <button class=\"cb primary\" id=\"playBtn\" onclick=\"togglePlay()\">Play</button>\n"
"  <button class=\"cb\" onclick=\"next()\">Next</button>\n"
"  <button class=\"cb\" onclick=\"goTo(steps.length-1)\">Last</button>\n"
"  <div class=\"prog-wrap\">\n"
"    <div class=\"prog-track\"><div class=\"prog-fill\" id=\"pFill\"></div></div>\n"
"    <div class=\"step-ctr\" id=\"sCtr\">Step 0 / 0</div>\n"
"  </div>\n"
"  <span style=\"font-size:.72rem;color:#94a3b8;\">Speed:</span>\n"
"  <input type=\"range\" id=\"spd\" min=\"1\" max=\"30\" value=\"8\" style=\"width:65px;accent-color:#38bdf8;\" oninput=\"onSpeed()\">\n"
"  <span id=\"spdLbl\" style=\"font-size:.72rem;color:#94a3b8;\">8/s</span>\n"
"</div>\n"
"\n"
"<script>\n"
"function goBack() {\n"
"  if (window.opener) {\n"
"    window.close();\n"
"  } else {\n"
"    window.location.href = '/';\n"
"  }\n"
"}\n"
"// ── Constants ──────────────────────────────────────────────────────────────\n"
"const P=0, R=1, PR=2;\n"
"let steps=[], puzzle=null, result=null;\n"
"let gridStates=[], statCache=[], pruneLog=[];\n"
"let cur=-1, playing=false, rafId=null, lastRaf=0, speed=8;\n"
"\n"
"// ── Precompute all grid states in ONE O(n) pass ────────────────────────────\n"
"function precompute(){\n"
"  const n=steps.length;\n"
"  gridStates = new Array(n+1);\n"
"  statCache  = new Array(n+1);\n"
"  pruneLog   = new Array(n+1);\n"
"\n"
"  gridStates[0] = puzzle.map(r=>[...r]);\n"
"\n"
"  let pl=0,bt=0,pr=0;\n"
"  const recentPrunes=[];\n"
"\n"
"  for(let i=0;i<n;i++){\n"
"    const s=steps[i];\n"
"    const g=gridStates[i].map(r=>[...r]);\n"
"    if(s.t===P){ g[s.r][s.c]=s.v; pl++; }\n"
"    if(s.t===R){ g[s.r][s.c]=0;   bt++; }\n"
"    if(s.t===PR){ pr++; recentPrunes.unshift({r:s.r,c:s.c}); if(recentPrunes.length>6)recentPrunes.pop(); }\n"
"    gridStates[i+1] = g;\n"
"    statCache[i]    = {pl,bt,pr};\n"
"    pruneLog[i]     = [...recentPrunes];\n"
"  }\n"
"  statCache[n] = statCache[n-1]||{pl:0,bt:0,pr:0};\n"
"}\n"
"\n"
"// ── Constraint analysis for a cell ────────────────────────────────────────\n"
"function analyzeCell(gridBefore, r, c){\n"
"  const br = 3*Math.floor(r/3);\n"
"  const bc = 3*Math.floor(c/3);\n"
"  const rowSet=new Set(), colSet=new Set(), blkSet=new Set();\n"
"\n"
"  for(let i=0;i<9;i++){\n"
"    if(gridBefore[r][i] && i!==c) rowSet.add(gridBefore[r][i]);\n"
"    if(gridBefore[i][c] && i!==r) colSet.add(gridBefore[i][c]);\n"
"  }\n"
"  for(let i=br;i<br+3;i++)\n"
"    for(let j=bc;j<bc+3;j++)\n"
"      if(!(i===r&&j===c)&&gridBefore[i][j]) blkSet.add(gridBefore[i][j]);\n"
"\n"
"  const eliminated = new Set([...rowSet,...colSet,...blkSet]);\n"
"  const candidates = [1,2,3,4,5,6,7,8,9].filter(d=>!eliminated.has(d));\n"
"\n"
"  return {\n"
"    rowSet, colSet, blkSet,\n"
"    eliminated, candidates,\n"
"    br, bc,\n"
"    blockName:`Block (${Math.floor(r/3)+1},${Math.floor(c/3)+1})`\n"
"  };\n"
"}\n"
"\n"
"// ── Find which empty cell in row/col/box has 0 candidates (Forward Check) ──\n"
"function findFailedCell(gridBefore, r, c, val) {\n"
"  const tempGrid = gridBefore.map(row => [...row]);\n"
"  tempGrid[r][c] = val; // simulate placement\n"
"  \n"
"  // Row check\n"
"  for (let col = 0; col < 9; col++) {\n"
"    if (col !== c && tempGrid[r][col] === 0) {\n"
"      const a = analyzeCell(tempGrid, r, col);\n"
"      if (a.candidates.length === 0) return { r: r, c: col, analysis: a };\n"
"    }\n"
"  }\n"
"  // Col check\n"
"  for (let row = 0; row < 9; row++) {\n"
"    if (row !== r && tempGrid[row][c] === 0) {\n"
"      const a = analyzeCell(tempGrid, row, c);\n"
"      if (a.candidates.length === 0) return { r: row, c: c, analysis: a };\n"
"    }\n"
"  }\n"
"  // Box check\n"
"  const br = 3 * Math.floor(r / 3);\n"
"  const bc = 3 * Math.floor(c / 3);\n"
"  for (let row = br; row < br + 3; row++) {\n"
"    for (let col = bc; col < bc + 3; col++) {\n"
"      if ((row !== r || col !== c) && tempGrid[row][col] === 0) {\n"
"        const a = analyzeCell(tempGrid, row, col);\n"
"        if (a.candidates.length === 0) return { r: row, c: col, analysis: a };\n"
"      }\n"
"    }\n"
"  }\n"
"  return null;\n"
"}\n"
"\n"
"// ── Digit pill HTML ───────────────────────────────────────────────────────\n"
"function dpHtml(d, cls){ return `<span class=\"digit-pill ${cls}\">${d}</span>`; }\n"
"\n"
"function digitRow(label, set, style){\n"
"  if(!set||set.size===0) return `<div style=\"font-size:.72rem;color:#94a3b8;margin-top:4px;\">${label}: <em>none</em></div>`;\n"
"  const pills=[...set].sort().map(d=>dpHtml(d,style)).join('');\n"
"  return `<div style=\"margin-top:4px;font-size:.72rem;\"><span style=\"color:#94a3b8;\">${label}:</span> ${pills}</div>`;\n"
"}\n"
"\n"
"// ── Build info panel HTML ─────────────────────────────────────────────────\n"
"function buildInfo(idx){\n"
"  const st = idx>=0 ? statCache[idx] : {pl:0,bt:0,pr:0};\n"
"  const prunes = idx>=0 ? pruneLog[idx] : [];\n"
"  let h='';\n"
"\n"
"  if(idx<0){\n"
"    // Initial state\n"
"    h+=`<div class=\"icard\">\n"
"      <h3>Starting State</h3>\n"
"      <div class=\"constraint-block result-c\">\n"
"        <div class=\"cbl-title\" style=\"color:#38bdf8;\">Initial Puzzle Loaded</div>\n"
"        Branch &amp; Bound will now select the <strong>most constrained empty cell</strong> first\n"
"        (Minimum Remaining Values = fewest valid candidates), then apply row + column + block\n"
"        constraints to prune invalid branches before recursing.\n"
"      </div>\n"
"    </div>`;\n"
"  } else {\n"
"    const s = steps[idx];\n"
"    const gridBefore = gridStates[idx]; // state BEFORE this step\n"
"\n"
"    if(s.t === P){\n"
"      const a = analyzeCell(gridBefore, s.r, s.c);\n"
"      const rowElim   = [...a.rowSet].sort();\n"
"      const colElim   = [...a.colSet].sort();\n"
"      const blkElim   = [...a.blkSet].sort();\n"
"      const chosen    = s.v;\n"
"      const otherCands= a.candidates.filter(d=>d!==chosen);\n"
"\n"
"      h+=`<div class=\"icard\">\n"
"        <h3>Step ${idx+1} &mdash; PLACE</h3>\n"
"        <div style=\"font-size:.9rem;font-weight:700;color:#38bdf8;margin-bottom:10px;\">\n"
"          Placed <span style=\"font-size:1.1rem;\">${chosen}</span> &rarr; Row ${s.r+1}, Col ${s.c+1}\n"
"        </div>\n"
"\n"
"        <!-- MRV -->\n"
"        <div class=\"constraint-block result-c\">\n"
"          <div class=\"cbl-title\" style=\"color:#38bdf8;\">Cell Selection (MRV Heuristic)</div>\n"
"          Cell (R${s.r+1}, C${s.c+1}) was selected because it has the\n"
"          <strong>fewest valid candidates (${a.candidates.length})</strong> among all empty cells.\n"
"          Choosing the most constrained cell first minimises branching and detects dead ends earlier.\n"
"        </div>\n"
"\n"
"        <!-- Row constraint -->\n"
"        <div class=\"constraint-block row-c\">\n"
"          <div class=\"cbl-title\" style=\"color:#38bdf8;\">Row ${s.r+1} Constraint</div>\n"
"          Digits already in Row ${s.r+1}:\n"
"          ${rowElim.length ? rowElim.map(d=>dpHtml(d,'dp-elim')).join(' ') : '<em style=\"color:#94a3b8;\">none</em>'}\n"
"          <br><small style=\"color:#94a3b8;\">These digits are eliminated from (R${s.r+1},C${s.c+1}).</small>\n"
"        </div>\n"
"\n"
"        <!-- Column constraint -->\n"
"        <div class=\"constraint-block col-c\">\n"
"          <div class=\"cbl-title\" style=\"color:#4ade80;\">Column ${s.c+1} Constraint</div>\n"
"          Digits already in Col ${s.c+1}:\n"
"          ${colElim.length ? colElim.map(d=>dpHtml(d,'dp-elim')).join(' ') : '<em style=\"color:#94a3b8;\">none</em>'}\n"
"          <br><small style=\"color:#94a3b8;\">These digits are eliminated from (R${s.r+1},C${s.c+1}).</small>\n"
"        </div>\n"
"\n"
"        <!-- Block constraint -->\n"
"        <div class=\"constraint-block blk-c\">\n"
"          <div class=\"cbl-title\" style=\"color:#fcd34d;\">${a.blockName} Constraint</div>\n"
"          br = 3&times;&#8970;${s.r}/3&#8971; = ${a.br} &nbsp;|&nbsp; bc = 3&times;&#8970;${s.c}/3&#8971; = ${a.bc}<br>\n"
"          Digits already in ${a.blockName}:\n"
"          ${blkElim.length ? blkElim.map(d=>dpHtml(d,'dp-elim')).join(' ') : '<em style=\"color:#94a3b8;\">none</em>'}\n"
"          <br><small style=\"color:#94a3b8;\">Block feasibility bound: if d already in block &rarr; prune.</small>\n"
"        </div>\n"
"\n"
"        <!-- Result -->\n"
"        <div class=\"constraint-block result-c\">\n"
"          <div class=\"cbl-title\" style=\"color:#38bdf8;\">Placement Decision</div>\n"
"          After applying all three constraints:<br>\n"
"          Valid candidates: ${a.candidates.map(d=>dpHtml(d, d===chosen?'dp-chosen':'dp-ok')).join(' ')}\n"
"          <br><br>\n"
"          ${dpHtml(chosen,'dp-chosen')} <strong>${chosen}</strong> is NOT in Row ${s.r+1}, Col ${s.c+1}, or ${a.blockName} &rarr; <strong style=\"color:#4ade80;\">VALID &mdash; Placed!</strong>\n"
"          <br><br>\n"
"          <strong>Forward Check:</strong> After placing ${chosen}, all neighbouring empty cells were verified to still have &ge;1 valid candidate &rarr; branch continues.\n"
"        </div>\n"
"      </div>`;\n"
"\n"
"    } else if(s.t === R){\n"
"      const a = analyzeCell(gridBefore, s.r, s.c);\n"
"      h+=`<div class=\"icard\">\n"
"        <h3>Step ${idx+1} &mdash; BACKTRACK</h3>\n"
"        <div style=\"font-size:.9rem;font-weight:700;color:#f87171;margin-bottom:10px;\">\n"
"          Undo placement at Row ${s.r+1}, Col ${s.c+1}\n"
"        </div>\n"
"        <div class=\"constraint-block bt-c2\">\n"
"          <div class=\"cbl-title\" style=\"color:#f87171;\">Why Backtrack?</div>\n"
"          A downstream cell was reached where <strong>all 9 digits were eliminated</strong>\n"
"          by its row, column, and block constraints &mdash; leaving 0 valid candidates.<br><br>\n"
"          There is no valid Sudoku completion possible from this partial board.\n"
"          We <strong>undo the last placement</strong> and return to the previous decision node\n"
"          to try the next candidate digit.\n"
"        </div>\n"
"        <div class=\"constraint-block blk-c\">\n"
"          <div class=\"cbl-title\" style=\"color:#fcd34d;\">Current Cell Analysis (R${s.r+1},C${s.c+1})</div>\n"
"          Row digits: ${[...a.rowSet].sort().map(d=>dpHtml(d,'dp-elim')).join(' ')||'<em style=\"color:#94a3b8;\">none</em>'}<br>\n"
"          Col digits: ${[...a.colSet].sort().map(d=>dpHtml(d,'dp-elim')).join(' ')||'<em style=\"color:#94a3b8;\">none</em>'}<br>\n"
"          Block (${a.blockName}): ${[...a.blkSet].sort().map(d=>dpHtml(d,'dp-elim')).join(' ')||'<em style=\"color:#94a3b8;\">none</em>'}\n"
"        </div>\n"
"      </div>`;\n"
"\n"
"    } else { // PRUNE\n"
"      const prevStep = idx > 0 ? steps[idx - 1] : null;\n"
"      let failedCell = null;\n"
"      if (prevStep && prevStep.t === P && prevStep.r === s.r && prevStep.c === s.c) {\n"
"        failedCell = findFailedCell(gridBefore, s.r, s.c, prevStep.v);\n"
"      }\n"
"\n"
"      if (failedCell) {\n"
"        const a = failedCell.analysis;\n"
"        const allElim = [...a.eliminated].sort();\n"
"        const blkElim = [...a.blkSet].sort();\n"
"        const rowElim = [...a.rowSet].sort();\n"
"        const colElim = [...a.colSet].sort();\n"
"\n"
"        h+=`<div class=\"icard\">\n"
"          <h3>Step ${idx+1} &mdash; BRANCH PRUNED</h3>\n"
"          <div style=\"font-size:.9rem;font-weight:700;color:#fb923c;margin-bottom:10px;\">\n"
"            Forward Check Failed at Row ${failedCell.r+1}, Col ${failedCell.c+1}\n"
"          </div>\n"
"          <div class=\"constraint-block prune-c\">\n"
"            <div class=\"cbl-title\" style=\"color:#fb923c;\">Bounding Condition Triggered</div>\n"
"            Placing <strong>${prevStep.v}</strong> at (R${s.r+1}, C${s.c+1}) eliminated all candidates for empty cell <strong>(R${failedCell.r+1}, C${failedCell.c+1})</strong>.<br><br>\n"
"            All 9 digits are eliminated:<br><br>\n"
"            ${allElim.map(d=>dpHtml(d,'dp-elim')).join(' ')}\n"
"          </div>\n"
"          <div class=\"constraint-block blk-c\">\n"
"            <div class=\"cbl-title\" style=\"color:#fcd34d;\">Empty Cell (R${failedCell.r+1}, C${failedCell.c+1}) Analysis</div>\n"
"            Box: ${a.blockName} has: ${blkElim.map(d=>dpHtml(d,'dp-elim')).join(' ')||'<em>none</em>'}<br>\n"
"            Row ${failedCell.r+1} has: ${rowElim.map(d=>dpHtml(d,'dp-elim')).join(' ')||'<em>none</em>'}<br>\n"
"            Col ${failedCell.c+1} has: ${colElim.map(d=>dpHtml(d,'dp-elim')).join(' ')||'<em>none</em>'}<br><br>\n"
"            Union = {${allElim.join(',')}} &rarr; all 9 digits covered &rarr; <strong style=\"color:#f87171;\">INFEASIBLE</strong>.\n"
"          </div>\n"
"        </div>`;\n"
"      } else {\n"
"        const a = analyzeCell(gridBefore, s.r, s.c);\n"
"        const allElim = [...a.eliminated].sort();\n"
"        const blkElim = [...a.blkSet].sort();\n"
"        const rowElim = [...a.rowSet].sort();\n"
"        const colElim = [...a.colSet].sort();\n"
"\n"
"        h+=`<div class=\"icard\">\n"
"          <h3>Step ${idx+1} &mdash; BRANCH PRUNED</h3>\n"
"          <div style=\"font-size:.9rem;font-weight:700;color:#fb923c;margin-bottom:10px;\">\n"
"            No candidates for Row ${s.r+1}, Col ${s.c+1}\n"
"          </div>\n"
"          <div class=\"constraint-block prune-c\">\n"
"            <div class=\"cbl-title\" style=\"color:#fb923c;\">Bounding Condition Triggered</div>\n"
"            Cell <strong>(R${s.r+1}, C${s.c+1})</strong> has <strong>0 valid candidates</strong> before placing any digit.<br><br>\n"
"            All 9 digits are eliminated:<br><br>\n"
"            ${allElim.map(d=>dpHtml(d,'dp-elim')).join(' ')}\n"
"          </div>\n"
"          <div class=\"constraint-block blk-c\">\n"
"            <div class=\"cbl-title\" style=\"color:#fcd34d;\">Cell (R${s.r+1}, C${s.c+1}) Analysis</div>\n"
"            Box: ${a.blockName} has: ${blkElim.map(d=>dpHtml(d,'dp-elim')).join(' ')||'<em>none</em>'}<br>\n"
"            Row ${s.r+1} has: ${rowElim.map(d=>dpHtml(d,'dp-elim')).join(' ')||'<em>none</em>'}<br>\n"
"            Col ${s.c+1} has: ${colElim.map(d=>dpHtml(d,'dp-elim')).join(' ')||'<em>none</em>'}<br><br>\n"
"            Union = {${allElim.join(',')}} &rarr; all 9 digits covered &rarr; <strong style=\"color:#f87171;\">INFEASIBLE</strong>.\n"
"          </div>\n"
"        </div>`;\n"
"      }\n"
"    }\n"
"  }\n"
"\n"
"  // Live stats always shown\n"
"  h+=`<div class=\"icard\">\n"
"    <h3>Journey Stats</h3>\n"
"    <div class=\"irow\"><span class=\"lbl\">Step</span><span class=\"val\" style=\"color:#38bdf8;\">${Math.max(0,idx+1)} / ${steps.length}</span></div>\n"
"    <div class=\"irow\"><span class=\"lbl\">Cells Placed</span><span class=\"val\" style=\"color:#4ade80;\">${st.pl}</span></div>\n"
"    <div class=\"irow\"><span class=\"lbl\">Backtracks</span><span class=\"val\" style=\"color:#f87171;\">${st.bt}</span></div>\n"
"    <div class=\"irow\"><span class=\"lbl\">Branches Pruned</span><span class=\"val\" style=\"color:#fb923c;\">${st.pr}</span></div>\n"
"    <div class=\"irow\"><span class=\"lbl\">Total Steps</span><span class=\"val\">${steps.length}</span></div>\n"
"    ${result?`<div class=\"irow\"><span class=\"lbl\">Solve Time</span><span class=\"val\" style=\"color:#38bdf8;\">${result.executionTimeMs.toFixed(2)}ms</span></div>`:''}\n"
"  </div>`;\n"
"\n"
"  if(prunes.length){\n"
"    h+=`<div class=\"icard\"><h3>Recent Pruned Routes</h3>\n"
"      ${prunes.map(p=>`<div style=\"font-size:.72rem;color:#fb923c;padding:3px 6px;background:rgba(251,146,60,.07);border:1px solid rgba(251,146,60,.14);border-radius:4px;margin-bottom:3px;\">Cell R${p.r+1}, C${p.c+1} &mdash; 0 candidates</div>`).join('')}\n"
"    </div>`;\n"
"  }\n"
"\n"
"  document.getElementById('iPanel').innerHTML=h;\n"
"}\n"
"\n"
"// ── Render sudoku grid ─────────────────────────────────────────────────────\n"
"function renderGrid(idx){\n"
"  const g    = gridStates[idx+1];\n"
"  const s    = idx>=0 ? steps[idx] : null;\n"
"  const el   = document.getElementById('sGrid');\n"
"  const cap  = document.getElementById('gridCaption');\n"
"\n"
"  // Determine active block\n"
"  let abr=-1,abc=-1;\n"
"  if(s){ abr=3*Math.floor(s.r/3); abc=3*Math.floor(s.c/3); }\n"
"\n"
"  if(!el.children.length){\n"
"    for(let i=0;i<81;i++){\n"
"      const c=document.createElement('div');\n"
"      c.className='sc';\n"
"      el.appendChild(c);\n"
"    }\n"
"  }\n"
"  const cells=el.children;\n"
"  for(let r=0;r<9;r++){\n"
"    for(let c=0;c<9;c++){\n"
"      const cell=cells[r*9+c];\n"
"      const val=g[r][c];\n"
"      cell.textContent=val||'';\n"
"      let cls='sc';\n"
"      if(c===2||c===5) cls+=' br';\n"
"      if(r===2||r===5) cls+=' bb';\n"
"      const isActive=s&&s.r===r&&s.c===c;\n"
"      const inBlock=abr>=0&&r>=abr&&r<abr+3&&c>=abc&&c<abc+3;\n"
"      if(isActive&&s.t===P)        cls+=' active-c';\n"
"      else if(isActive&&s.t===R)   cls+=' bt-c';\n"
"      else if(isActive&&s.t===PR)  cls+=' pr-c';\n"
"      else if(puzzle[r][c]!==0)    cls+=' fixed';\n"
"      else if(val!==0)             cls+=' placed';\n"
"      else                         cls+=' empty';\n"
"      if(inBlock&&!isActive)       cls+=' block-hl';\n"
"      cell.className=cls;\n"
"    }\n"
"  }\n"
"  if(s){\n"
"    if(s.t===P)  cap.textContent=`Step ${idx+1}: Placed ${s.v} at Row ${s.r+1}, Col ${s.c+1}`;\n"
"    else if(s.t===R) cap.textContent=`Step ${idx+1}: Backtrack from Row ${s.r+1}, Col ${s.c+1}`;\n"
"    else         cap.textContent=`Step ${idx+1}: Pruned branch at Row ${s.r+1}, Col ${s.c+1}`;\n"
"  } else {\n"
"    cap.textContent='Initial Puzzle';\n"
"  }\n"
"}\n"
"\n"
"// ── Virtual road (window of 40 steps) ─────────────────────────────────────\n"
"const VWIN=40; let rStart=0,rEnd=0;\n"
"function buildRoad(idx){\n"
"  const s=Math.max(0,(idx-VWIN/2)|0);\n"
"  const e=Math.min(steps.length-1,s+VWIN);\n"
"  if(s===rStart&&e===rEnd) return;\n"
"  rStart=s;rEnd=e;\n"
"  const frag=document.createDocumentFragment();\n"
"  for(let i=s;i<=e;i++){\n"
"    const st=steps[i];\n"
"    const el=document.createElement('div');\n"
"    el.className='road-step'+(i===idx?' active':'');\n"
"    el.id='rs'+i;\n"
"    el.onclick=(function(ii){return function(){goTo(ii);};})(i);\n"
"    let dc,dt,tl,ct;\n"
"    if(st.t===P){dc='#38bdf8';dt='P';tl='PLACE';ct=`R${st.r+1}C${st.c+1}=${st.v}`;}\n"
"    else if(st.t===R){dc='#f87171';dt='B';tl='BACKTRACK';ct=`Undo R${st.r+1}C${st.c+1}`;}\n"
"    else{dc='#fb923c';dt='X';tl='PRUNED';ct=`Dead end R${st.r+1}C${st.c+1}`;}\n"
"    el.innerHTML=`<div class=\"road-dot\" style=\"background:${dc};color:#060b13;\">${dt}</div>\n"
"      <div class=\"road-card\"><div class=\"step-type-lbl\" style=\"color:${dc}\">${tl}</div><div>${ct}</div></div>`;\n"
"    frag.appendChild(el);\n"
"  }\n"
"  const inner=document.getElementById('roadInner');\n"
"  inner.innerHTML='';inner.appendChild(frag);\n"
"}\n"
"function hlRoad(idx){\n"
"  document.querySelectorAll('.road-step').forEach(el=>el.classList.toggle('active',el.id==='rs'+idx));\n"
"  const el=document.getElementById('rs'+idx);\n"
"  if(el)el.scrollIntoView({block:'nearest',behavior:'smooth'});\n"
"}\n"
"\n"
"// ── Navigation ─────────────────────────────────────────────────────────────\n"
"function goTo(idx){\n"
"  idx=Math.max(-1,Math.min(steps.length-1,idx));\n"
"  cur=idx;\n"
"  renderGrid(idx);\n"
"  buildInfo(idx);\n"
"  buildRoad(idx);\n"
"  hlRoad(idx);\n"
"  const pct=steps.length?((idx+1)/steps.length*100):0;\n"
"  document.getElementById('pFill').style.width=pct+'%';\n"
"  document.getElementById('sCtr').textContent=`Step ${Math.max(0,idx+1)} / ${steps.length}`;\n"
"}\n"
"function next(){if(cur<steps.length-1)goTo(cur+1);else pause();}\n"
"function prev(){if(cur>-1)goTo(cur-1);}\n"
"function togglePlay(){playing?pause():play();}\n"
"function play(){\n"
"  if(cur>=steps.length-1)goTo(-1);\n"
"  playing=true;document.getElementById('playBtn').textContent='Pause';\n"
"  lastRaf=0;rafId=requestAnimationFrame(tick);\n"
"}\n"
"function pause(){\n"
"  playing=false;document.getElementById('playBtn').textContent='Play';\n"
"  if(rafId){cancelAnimationFrame(rafId);rafId=null;}\n"
"}\n"
"function tick(ts){\n"
"  if(!playing)return;\n"
"  if(ts-lastRaf>=1000/speed){lastRaf=ts;next();}\n"
"  rafId=requestAnimationFrame(tick);\n"
"}\n"
"function onSpeed(){\n"
"  speed=parseInt(document.getElementById('spd').value);\n"
"  document.getElementById('spdLbl').textContent=speed+'/s';\n"
"}\n"
"document.addEventListener('keydown',e=>{\n"
"  if(e.key==='ArrowRight')next();\n"
"  else if(e.key==='ArrowLeft')prev();\n"
"  else if(e.key===' '){e.preventDefault();togglePlay();}\n"
"});\n"
"\n"
"// ── Header stats ───────────────────────────────────────────────────────────\n"
"function renderHeader(){\n"
"  const tp=steps.filter(s=>s.t===PR).length;\n"
"  const tb=steps.filter(s=>s.t===R).length;\n"
"  const tpl=steps.filter(s=>s.t===P).length;\n"
"  document.getElementById('hStats').innerHTML=`\n"
"    <div class=\"stat-pill\">Steps: <strong>${steps.length}</strong></div>\n"
"    <div class=\"stat-pill\" style=\"color:#4ade80;\">Placed: <strong>${tpl}</strong></div>\n"
"    <div class=\"stat-pill\" style=\"color:#f87171;\">Backtracks: <strong>${tb}</strong></div>\n"
"    <div class=\"stat-pill\" style=\"color:#fb923c;\">Pruned: <strong>${tp}</strong></div>\n"
"    ${result?`<div class=\"stat-pill\" style=\"color:#38bdf8;\">${result.executionTimeMs.toFixed(2)}ms</div>`:''}\n"
"  `;\n"
"}\n"
"\n"
"// ── Init ───────────────────────────────────────────────────────────────────\n"
"function init(){\n"
"  const sr=localStorage.getItem('journey_steps');\n"
"  const pr=localStorage.getItem('journey_puzzle');\n"
"  const rr=localStorage.getItem('journey_result');\n"
"  if(!sr||!pr)return;\n"
"  clearInterval(pollId);\n"
"  steps=JSON.parse(sr);puzzle=JSON.parse(pr);result=rr?JSON.parse(rr):null;\n"
"  document.getElementById('loader').style.display='none';\n"
"  precompute();\n"
"  renderHeader();\n"
"  goTo(-1);\n"
"}\n"
"const pollId=setInterval(init,150);\n"
"init();\n"
"</script>\n"
"</body>\n"
"</html>\n"
"\n";
