/* gui_html.c - Embedded HTML/CSS/JS frontend as a C string */
const char *GUI_HTML =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <title>Sudoku Solver - DAA Mini Project</title>\n"
"  <link rel=\"icon\" href=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=\">\n"
"  <link href=\"https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter:wght@400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n"
"  <style>\n"
"    :root {\n"
"      --font-display: 'Instrument Serif', serif;\n"
"      --font-body: 'Inter', sans-serif;\n"
"      --background: 201 100% 13%;\n"
"      --foreground: 0 0% 100%;\n"
"      --muted-foreground: 240 4% 66%;\n"
"    }\n"
"    * { margin: 0; padding: 0; box-sizing: border-box; }\n"
"    body {\n"
"      font-family: var(--font-body);\n"
"      background-color: hsl(var(--background));\n"
"      color: hsl(var(--foreground));\n"
"      min-height: 100vh;\n"
"      overflow-x: hidden;\n"
"    }\n"
"    \n"
"    /* Liquid Glass Effect */\n"
"    .liquid-glass {\n"
"      background: rgba(255, 255, 255, 0.01);\n"
"      background-blend-mode: luminosity;\n"
"      backdrop-filter: blur(4px);\n"
"      -webkit-backdrop-filter: blur(4px);\n"
"      border: none;\n"
"      box-shadow: inset 0 1px 1px rgba(255, 255, 255, 0.1);\n"
"      position: relative;\n"
"      overflow: hidden;\n"
"      cursor: pointer;\n"
"      transition: transform 0.2s, background 0.2s;\n"
"    }\n"
"    .liquid-glass::before {\n"
"      content: '';\n"
"      position: absolute;\n"
"      inset: 0;\n"
"      border-radius: inherit;\n"
"      padding: 1.4px;\n"
"      background: linear-gradient(180deg,\n"
"        rgba(255,255,255,0.45) 0%, rgba(255,255,255,0.15) 20%,\n"
"        rgba(255,255,255,0) 40%, rgba(255,255,255,0) 60%,\n"
"        rgba(255,255,255,0.15) 80%, rgba(255,255,255,0.45) 100%);\n"
"      -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);\n"
"      -webkit-mask-composite: xor;\n"
"      mask-composite: exclude;\n"
"      pointer-events: none;\n"
"    }\n"
"    .liquid-glass:hover { transform: scale(1.03); background: rgba(255, 255, 255, 0.05); }\n"
"    \n"
"    .nav-btn {\n"
"      padding: 0.625rem 1.5rem;\n"
"      border-radius: 9999px;\n"
"      font-size: 0.875rem;\n"
"      color: hsl(var(--foreground));\n"
"      font-family: var(--font-body);\n"
"    }\n"
"    \n"
"    /* Hero Section */\n"
"    .hero {\n"
"      position: relative;\n"
"      z-index: 10;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      align-items: center;\n"
"      text-align: center;\n"
"      padding: 90px 1.5rem 6rem;\n"
"    }\n"
"    .hero h1 {\n"
"      font-family: var(--font-display);\n"
"      font-size: clamp(3rem, 8vw, 6rem);\n"
"      font-weight: 400;\n"
"      line-height: 0.95;\n"
"      letter-spacing: -2.46px;\n"
"      max-width: 80rem;\n"
"      margin: 0;\n"
"    }\n"
"    .hero h1 em {\n"
"      font-style: normal;\n"
"      color: hsl(var(--muted-foreground));\n"
"    }\n"
"    .hero-subtext {\n"
"      color: hsl(var(--muted-foreground));\n"
"      font-size: clamp(1rem, 2vw, 1.125rem);\n"
"      max-width: 42rem;\n"
"      margin-top: 2rem;\n"
"      line-height: 1.625;\n"
"    }\n"
"    \n"
"    /* Difficulty Cards */\n"
"    .diff-cards {\n"
"      display: flex;\n"
"      gap: 20px;\n"
"      margin-top: 3rem;\n"
"      flex-wrap: wrap;\n"
"      justify-content: center;\n"
"    }\n"
"    .diff-card {\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      align-items: center;\n"
"      padding: 2rem 2.5rem;\n"
"      border-radius: 20px;\n"
"      width: 220px;\n"
"      color: hsl(var(--foreground));\n"
"      background: rgba(10, 18, 35, 0.7);\n"
"      backdrop-filter: blur(12px);\n"
"      -webkit-backdrop-filter: blur(12px);\n"
"      box-shadow: 0 8px 32px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.08);\n"
"      border: 1px solid rgba(255,255,255,0.1);\n"
"    }\n"
"    .diff-card h2 { font-size: 1.8rem; font-family: var(--font-display); margin-bottom: 0.5rem; }\n"
"    .diff-card p { font-size: 0.95rem; color: #fcd34d; font-weight: 500; }\n"
"    \n"
"    /* Animations */\n"
"    @keyframes fade-rise {\n"
"      from { opacity: 0; transform: translateY(24px); }\n"
"      to { opacity: 1; transform: translateY(0); }\n"
"    }\n"
"    .animate-fade-rise { animation: fade-rise 0.8s ease-out both; }\n"
"    .animate-fade-rise-delay { animation: fade-rise 0.8s ease-out 0.2s both; }\n"
"    .animate-fade-rise-delay-2 { animation: fade-rise 0.8s ease-out 0.4s both; }\n"
"\n"
"    /* Sudoku Container */\n"
"    .sudoku-section {\n"
"      position: relative;\n"
"      z-index: 10;\n"
"      margin-top: 20px;\n"
"      padding-bottom: 60px;\n"
"    }\n"
"    .container {\n"
"      max-width: 1100px;\n"
"      margin: 0 auto;\n"
"      padding: 24px;\n"
"      display: flex;\n"
"      flex-wrap: wrap;\n"
"      gap: 32px;\n"
"      justify-content: center;\n"
"    }\n"
"    .grid-wrap {\n"
"      background: rgba(10, 18, 35, 0.5);\n"
"      border-radius: 16px;\n"
"      padding: 20px;\n"
"      box-shadow: 0 8px 32px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.08);\n"
"      backdrop-filter: blur(12px);\n"
"      -webkit-backdrop-filter: blur(12px);\n"
"    }\n"
"    table { border-collapse: collapse; }\n"
"    td {\n"
"      width: 54px; height: 54px; text-align: center; font-size: 1.35rem; font-weight: 600;\n"
"      border: 1px solid rgba(255,255,255,0.08); cursor: pointer; position: relative; transition: background 0.15s;\n"
"    }\n"
"    td:hover { background: rgba(255,255,255,0.08); }\n"
"    td.fixed { color: hsl(var(--foreground)); font-weight: 700; }\n"
"    td.user { color: #fcd34d; }\n"
"    td.error { color: #ef4444; background: rgba(239,68,68,0.1); }\n"
"    td.selected { background: rgba(255,255,255,0.12) !important; box-shadow: inset 0 0 0 2px rgba(255,255,255,0.4); }\n"
"    td.hl-row-col { background: rgba(255,255,255,0.04); }\n"
"    td.anim-place { background: rgba(56,189,248,0.3) !important; transition: background 0.08s; }\n"
"    td.anim-remove { background: rgba(239,68,68,0.3) !important; transition: background 0.08s; }\n"
"    td.anim-prune { background: rgba(251,191,36,0.3) !important; transition: background 0.08s; }\n"
"    td.hint-cell { background: rgba(252,211,77,0.2) !important; animation: hintPulse 1s ease-in-out 3; }\n"
"    @keyframes hintPulse { 0%, 100% { box-shadow: inset 0 0 0 2px transparent; } 50% { box-shadow: inset 0 0 0 2px #fcd34d; } }\n"
"    td.solved-anim { color: #38bdf8; }\n"
"    .thick-right { border-right: 2.5px solid rgba(255,255,255,0.25) !important; }\n"
"    .thick-bottom { border-bottom: 2.5px solid rgba(255,255,255,0.25) !important; }\n"
"    .thick-left { border-left: 2.5px solid rgba(255,255,255,0.25) !important; }\n"
"    .thick-top { border-top: 2.5px solid rgba(255,255,255,0.25) !important; }\n"
"    \n"
"    .panel { display: flex; flex-direction: column; gap: 12px; min-width: 280px; }\n"
"    \n"
"    .section-title { font-size: 0.75rem; font-weight: 700; color: hsl(var(--muted-foreground)); text-transform: uppercase; letter-spacing: 1.5px; margin-top: 8px; }\n"
"    \n"
"    .stats-box { background: rgba(255,255,255,0.03); border-radius: 12px; padding: 14px; border: 1px solid rgba(255,255,255,0.08); backdrop-filter: blur(6px); }\n"
"    .stats-box h3 { font-size: 0.8rem; color: hsl(var(--muted-foreground)); margin-bottom: 8px; font-weight: 600; }\n"
"    .stat-row { display: flex; justify-content: space-between; align-items: center; font-size: 0.8rem; padding: 3px 0; }\n"
"    .stat-label { color: hsl(var(--muted-foreground)); } .stat-val { color: #7dd3fc; font-weight: 600; }\n"
"    .stat-val.bb { color: #fcd34d; }\n"
"    .stat-val.ratio { color: #022c22; background: #4ade80; padding: 3px 8px; border-radius: 6px; font-size: 0.8rem; font-weight: 800; box-shadow: 0 0 12px rgba(74, 222, 128, 0.45); }\n"
"    \n"
"    .legend { display: flex; gap: 16px; flex-wrap: wrap; margin-top: 8px; }\n"
"    .legend-item { display: flex; align-items: center; gap: 5px; font-size: 0.72rem; color: hsl(var(--muted-foreground)); }\n"
"    .legend-color { width: 14px; height: 14px; border-radius: 3px; }\n"
"    \n"
"    .anim-controls { font-size: 0.8rem; color: hsl(var(--muted-foreground)); }\n"
"    .anim-controls span { color: hsl(var(--foreground)); }\n"
"    .speed-display { font-size: 0.85rem; color: #7dd3fc; font-weight: 600; }\n"
"    .progress-bar { width: 100%; height: 4px; background: rgba(255,255,255,0.1); border-radius: 2px; overflow: hidden; margin-top: 4px; }\n"
"    .progress-fill { height: 100%; background: linear-gradient(90deg, #38bdf8, #fcd34d); border-radius: 2px; transition: width 0.1s; }\n"
"\n"
"    /* Transitions */\n"
"    .fade-out { opacity: 0; pointer-events: none; transition: opacity 0.3s; }\n"
"    .fade-in { opacity: 1; pointer-events: auto; transition: opacity 0.3s; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"\n"
"  <!-- Fullscreen Video Background -->\n"
"  <video autoplay loop muted playsinline src=\"https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260314_131748_f2ca2a28-fed7-44c8-b9a9-bd9acdd5ec31.mp4\" style=\"position:fixed;inset:0;width:100%;height:100%;object-fit:cover;z-index:0;pointer-events:none;\"></video>\n"
"\n"
"  <!-- HOME VIEW -->\n"
"  <div id=\"home-view\" class=\"fade-in\">\n"
"    <div class=\"hero\">\n"
"      <h1 class=\"animate-fade-rise\"><em>Master the grid.</em> Solve <em>with algorithms.</em></h1>\n"
"      <p class=\"hero-subtext animate-fade-rise-delay\">Experience the power of Backtracking and Branch & Bound algorithms. A blazing-fast, interactive Sudoku solver built for the DAA mini-project.</p>\n"
"      \n"
"      <div class=\"diff-cards animate-fade-rise-delay-2\">\n"
"        <button class=\"liquid-glass diff-card\" onclick=\"startLevel(0)\">\n"
"          <h2>Easy</h2>\n"
"          <p>30 blanks</p>\n"
"        </button>\n"
"        <button class=\"liquid-glass diff-card\" onclick=\"startLevel(1)\">\n"
"          <h2>Intermediate</h2>\n"
"          <p>40 blanks</p>\n"
"        </button>\n"
"        <button class=\"liquid-glass diff-card\" onclick=\"startLevel(2)\">\n"
"          <h2>Hard</h2>\n"
"          <p>50 blanks</p>\n"
"        </button>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <!-- SOLVER VIEW -->\n"
"  <div id=\"solver-view\" style=\"display: none;\" class=\"fade-in\">\n"
"    <div class=\"sudoku-section\">\n"
"      <div class=\"container\">\n"
"        <div class=\"grid-wrap\">\n"
"          <table id=\"grid\"></table>\n"
"          <div class=\"legend\">\n"
"            <div class=\"legend-item\"><div class=\"legend-color\" style=\"background:rgba(40,180,80,0.5)\"></div>Placing</div>\n"
"            <div class=\"legend-item\"><div class=\"legend-color\" style=\"background:rgba(200,50,50,0.5)\"></div>Backtrack</div>\n"
"            <div class=\"legend-item\"><div class=\"legend-color\" style=\"background:rgba(220,150,30,0.5)\"></div>Pruned</div>\n"
"            <div class=\"legend-item\"><div class=\"legend-color\" style=\"background:rgba(255,215,0,0.3)\"></div>Hint</div>\n"
"          </div>\n"
"        </div>\n"
"        <div class=\"panel\">\n"
"          <button class=\"liquid-glass nav-btn\" id=\"btnBack\" style=\"padding:10px 20px;font-size:0.85rem;margin-bottom:10px;\">← Back to Home</button>\n"
"          \n"
"          <button class=\"liquid-glass nav-btn\" id=\"btnGen\" style=\"padding:12px 20px;font-size:0.9rem;font-weight:600;\">Generate New Puzzle</button>\n"
"          <button class=\"liquid-glass nav-btn\" id=\"btnBT\" disabled style=\"padding:12px 20px;font-size:0.9rem;font-weight:600;\">Solve: Backtracking</button>\n"
"          <button class=\"liquid-glass nav-btn\" id=\"btnBB\" disabled style=\"padding:12px 20px;font-size:0.9rem;font-weight:600;\">Solve: Branch & Bound</button>\n"
"          <div style=\"display:flex;gap:10px;\">\n"
"            <button class=\"liquid-glass nav-btn\" id=\"btnReset\" disabled style=\"flex:1;padding:10px;font-size:0.85rem;opacity:0.8;\">Reset</button>\n"
"            <button class=\"liquid-glass nav-btn\" id=\"btnHint\" disabled style=\"flex:1;padding:10px;font-size:0.85rem;opacity:0.8;\">Hint</button>\n"
"          </div>\n"
"          \n"
"          <div class=\"section-title\">How to Play</div>\n"
"          <div class=\"stats-box\" style=\"font-size:0.78rem;line-height:1.45;color:hsl(var(--muted-foreground));padding:12px;display:flex;flex-direction:column;gap:5px\">\n"
"            <div><strong style=\"color:#7dd3fc\">Select cell:</strong> Click any cell in the grid</div>\n"
"            <div><strong style=\"color:#7dd3fc\">Input value:</strong> Press <strong style=\"color:#fcd34d\">1-9</strong></div>\n"
"            <div><strong style=\"color:#7dd3fc\">Erase value:</strong> Press <strong style=\"color:#ef4444\">Backspace</strong> or <strong style=\"color:#ef4444\">0</strong></div>\n"
"          </div>\n"
"          \n"
"          <div class=\"section-title\" id=\"animTitle\" style=\"display:none\">Animation</div>\n"
"          <div class=\"anim-controls\" id=\"animCtrl\" style=\"display:none\">\n"
"            <div class=\"speed-display\" id=\"speedDisp\"></div>\n"
"            <div class=\"progress-bar\"><div class=\"progress-fill\" id=\"progFill\"></div></div>\n"
"            <div style=\"margin-top:6px\"><span>[+/-]</span> Speed &nbsp; <span>[Space]</span> Pause</div>\n"
"            <div id=\"animActionText\" style=\"margin-top:10px; font-size:0.95rem; font-weight:600; color:#fcd34d;\"></div>\n"
"          </div>\n"
"          \n"
"          <div id=\"statsArea\"></div>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <script>\n"
"    const homeView=document.getElementById('home-view');\n"
"    const solverView=document.getElementById('solver-view');\n"
"    const grid=document.getElementById('grid');\n"
"    const btnGen=document.getElementById('btnGen');\n"
"    const btnBT=document.getElementById('btnBT');\n"
"    const btnBB=document.getElementById('btnBB');\n"
"    const btnReset=document.getElementById('btnReset');\n"
"    const btnHint=document.getElementById('btnHint');\n"
"    const btnBack=document.getElementById('btnBack');\n"
"    const animTitle=document.getElementById('animTitle');\n"
"    const animCtrl=document.getElementById('animCtrl');\n"
"    const speedDisp=document.getElementById('speedDisp');\n"
"    const progFill=document.getElementById('progFill');\n"
"    const statsArea=document.getElementById('statsArea');\n"
"    \n"
"    let currentDifficulty=0;\n"
"    let cells=[],puzzle=null,fixed=null,solution=null,selR=-1,selC=-1,preSolveGrid=null;\n"
"    let animating=false,animPaused=false,animSpeed=150,animSteps=[],animIdx=0,animTimer=null;\n"
"    let btStats=null,bbStats=null,dispGrid=null;\n"
"\n"
"    // View Routing\n"
"    function startLevel(diff){\n"
"      currentDifficulty=diff;\n"
"      homeView.classList.remove('fade-in');\n"
"      homeView.classList.add('fade-out');\n"
"      setTimeout(()=>{\n"
"        homeView.style.display='none';\n"
"        solverView.style.display='block';\n"
"        solverView.classList.remove('fade-out');\n"
"        solverView.classList.add('fade-in');\n"
"        generatePuzzle();\n"
"      },300);\n"
"    }\n"
"    \n"
"    btnBack.addEventListener('click',()=>{\n"
"      if(animating)return;\n"
"      solverView.classList.remove('fade-in');\n"
"      solverView.classList.add('fade-out');\n"
"      setTimeout(()=>{\n"
"        solverView.style.display='none';\n"
"        homeView.style.display='block';\n"
"        homeView.classList.remove('fade-out');\n"
"        homeView.classList.add('fade-in');\n"
"        puzzle=null; fixed=null; solution=null; preSolveGrid=null;\n"
"        grid.innerHTML=''; buildGrid();\n"
"        statsArea.innerHTML=''; btStats=null; bbStats=null;\n"
"        setButtonsEnabled(false); btnGen.disabled=false;\n"
"      },300);\n"
"    });\n"
"\n"
"    function buildGrid(){\n"
"      grid.innerHTML='';\n"
"      cells=[];\n"
"      for(let r=0;r<9;r++){\n"
"        const tr=document.createElement('tr');\n"
"        cells[r]=[];\n"
"        for(let c=0;c<9;c++){\n"
"          const td=document.createElement('td');\n"
"          if(c%3===2&&c<8)td.classList.add('thick-right');\n"
"          if(r%3===2&&r<8)td.classList.add('thick-bottom');\n"
"          if(c%3===0)td.classList.add('thick-left');\n"
"          if(r%3===0)td.classList.add('thick-top');\n"
"          td.dataset.r=r;td.dataset.c=c;\n"
"          td.addEventListener('click',()=>selectCell(r,c));\n"
"          tr.appendChild(td);\n"
"          cells[r][c]=td;\n"
"        }\n"
"        grid.appendChild(tr);\n"
"      }\n"
"    }\n"
"\n"
"    function renderGrid(g,f){\n"
"      for(let r=0;r<9;r++)for(let c=0;c<9;c++){\n"
"        const td=cells[r][c];\n"
"        td.textContent=g[r][c]||'';\n"
"        td.className='';\n"
"        if(c%3===2&&c<8)td.classList.add('thick-right');\n"
"        if(r%3===2&&r<8)td.classList.add('thick-bottom');\n"
"        if(c%3===0)td.classList.add('thick-left');\n"
"        if(r%3===0)td.classList.add('thick-top');\n"
"        if(f&&f[r][c])td.classList.add('fixed');\n"
"        else if(g[r][c])td.classList.add('user');\n"
"      }\n"
"    }\n"
"\n"
"    function selectCell(r,c){\n"
"      if(animating)return;\n"
"      document.querySelectorAll('td.selected,td.hl-row-col').forEach(e=>{\n"
"        e.classList.remove('selected','hl-row-col');\n"
"      });\n"
"      selR=r;selC=c;\n"
"      cells[r][c].classList.add('selected');\n"
"      for(let i=0;i<9;i++){cells[r][i].classList.add('hl-row-col');cells[i][c].classList.add('hl-row-col');}\n"
"      cells[r][c].classList.remove('hl-row-col');\n"
"      cells[r][c].classList.add('selected');\n"
"    }\n"
"\n"
"    function validateGrid(){\n"
"      if(!puzzle)return;\n"
"      for(let r=0;r<9;r++)for(let c=0;c<9;c++){\n"
"        cells[r][c].classList.remove('error');\n"
"        const v=puzzle[r][c];\n"
"        if(v&&!fixed[r][c]){\n"
"          let err=false;\n"
"          for(let i=0;i<9;i++){if(i!==c&&puzzle[r][i]===v)err=true;if(i!==r&&puzzle[i][c]===v)err=true;}\n"
"          const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;\n"
"          for(let dr=0;dr<3;dr++)for(let dc=0;dc<3;dc++){\n"
"            if(br+dr!==r||bc+dc!==c){if(puzzle[br+dr][bc+dc]===v)err=true;}\n"
"          }\n"
"          if(err)cells[r][c].classList.add('error');\n"
"        }\n"
"      }\n"
"    }\n"
"\n"
"    function checkUserWin(){\n"
"      let filled=true,hasError=false;\n"
"      for(let r=0;r<9;r++){\n"
"        for(let c=0;c<9;c++){\n"
"          if(!puzzle[r][c])filled=false;\n"
"          if(cells[r][c].classList.contains('error'))hasError=true;\n"
"        }\n"
"      }\n"
"      if(filled&&!hasError){\n"
"        statsArea.innerHTML='<div class=\"stats-box\" style=\"border-color:#fcd34d;background:rgba(252,211,77,.1);text-align:center\"><h3 style=\"color:#fcd34d;font-size:1.1rem;margin-bottom:4px\">✨ Congratulations!</h3><p style=\"font-size:.85rem;color:hsl(var(--foreground))\">You successfully solved the puzzle!</p></div>';\n"
"      }\n"
"    }\n"
"\n"
"    document.addEventListener('keydown',e=>{\n"
"      if(animating||!puzzle||solverView.style.display==='none'){\n"
"        if(animating){\n"
"          if(e.key==='='||e.key==='+'){animSpeed=Math.min(animSpeed*1.5,8000);speedDisp.textContent='Speed: '+Math.round(animSpeed)+' steps/sec';}\n"
"          if(e.key==='-'){animSpeed=Math.max(animSpeed/1.5,5);speedDisp.textContent='Speed: '+Math.round(animSpeed)+' steps/sec';}\n"
"          if(e.key===' '){animPaused=!animPaused;e.preventDefault();}\n"
"        }\n"
"        return;\n"
"      }\n"
"      if(selR<0||fixed[selR][selC])return;\n"
"      if(e.key>='1'&&e.key<='9'){puzzle[selR][selC]=parseInt(e.key);preSolveGrid=null;renderGrid(puzzle,fixed);selectCell(selR,selC);validateGrid();checkUserWin();}\n"
"      if(e.key==='Backspace'||e.key==='Delete'||e.key==='0'){puzzle[selR][selC]=0;preSolveGrid=null;renderGrid(puzzle,fixed);selectCell(selR,selC);validateGrid();}\n"
"      if(e.key==='ArrowUp'&&selR>0){selectCell(selR-1,selC);}\n"
"      if(e.key==='ArrowDown'&&selR<8){selectCell(selR+1,selC);}\n"
"      if(e.key==='ArrowLeft'&&selC>0){selectCell(selR,selC-1);}\n"
"      if(e.key==='ArrowRight'&&selC<8){selectCell(selR,selC+1);}\n"
"    });\n"
"\n"
"    async function apiPost(url,data){\n"
"      const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});\n"
"      return r.json();\n"
"    }\n"
"\n"
"    async function generatePuzzle(){\n"
"      btnGen.disabled=true;btnGen.textContent='Generating...';\n"
"      try{\n"
"        const d=await apiPost('/generate',{difficulty:currentDifficulty});\n"
"        puzzle=d.grid;fixed=d.fixed;solution=d.solution;\n"
"        preSolveGrid=null;\n"
"        renderGrid(puzzle,fixed);\n"
"        setButtonsEnabled(true);\n"
"        btStats=null;bbStats=null;statsArea.innerHTML='';\n"
"      }catch(e){alert('Error: '+e.message);}\n"
"      btnGen.disabled=false;btnGen.textContent='Generate New Puzzle';\n"
"    }\n"
"\n"
"    btnGen.addEventListener('click', generatePuzzle);\n"
"\n"
"    btnReset.addEventListener('click',()=>{\n"
"      if(!solution)return;\n"
"      for(let r=0;r<9;r++)for(let c=0;c<9;c++){if(!fixed[r][c])puzzle[r][c]=0;}\n"
"      preSolveGrid=null;\n"
"      renderGrid(puzzle,fixed);validateGrid();\n"
"      btStats=null;bbStats=null;statsArea.innerHTML='';\n"
"    });\n"
"\n"
"    btnHint.addEventListener('click',async()=>{\n"
"      if(!puzzle)return;\n"
"      try{\n"
"        const d=await apiPost('/hint',{grid:puzzle});\n"
"        if(d.found){\n"
"          puzzle[d.row][d.col]=d.value;renderGrid(puzzle,fixed);\n"
"          cells[d.row][d.col].classList.add('hint-cell');\n"
"          setTimeout(()=>cells[d.row][d.col].classList.remove('hint-cell'),3000);\n"
"          validateGrid();\n"
"        }\n"
"      }catch(e){}\n"
"    });\n"
"\n"
"    function setButtonsEnabled(en){\n"
"      btnBT.disabled=!en;btnBB.disabled=!en;btnReset.disabled=!en;btnHint.disabled=!en;\n"
"    }\n"
"\n"
"    function runAnimation(steps,result,label){\n"
"      animating=true;animPaused=false;animSteps=steps;animIdx=0;\n"
"      dispGrid=preSolveGrid.map(r=>[...r]);\n"
"      setButtonsEnabled(false); btnGen.disabled=true; btnBack.disabled=true;\n"
"      animTitle.style.display='block';animCtrl.style.display='block';\n"
"      speedDisp.textContent='Speed: '+Math.round(animSpeed)+' steps/sec';\n"
"\n"
"      function tick(){\n"
"        if(!animating)return;\n"
"        if(animPaused){animTimer=requestAnimationFrame(tick);return;}\n"
"        const stepsPerFrame=Math.max(1,Math.round(animSpeed/60));\n"
"        for(let i=0;i<stepsPerFrame&&animIdx<animSteps.length;i++){\n"
"          const s=animSteps[animIdx];\n"
"          document.querySelectorAll('td.anim-place,td.anim-remove,td.anim-prune').forEach(e=>{\n"
"            e.classList.remove('anim-place','anim-remove','anim-prune');\n"
"          });\n"
"          const actionText = document.getElementById('animActionText');\n"
"          if(s.t===0){dispGrid[s.r][s.c]=s.v;cells[s.r][s.c].textContent=s.v||'';cells[s.r][s.c].className='';addBorders(s.r,s.c);cells[s.r][s.c].classList.add('solved-anim','anim-place'); actionText.innerHTML='Placing <b>'+s.v+'</b> at Row '+(s.r+1)+' Col '+(s.c+1);}\n"
"          else if(s.t===1){dispGrid[s.r][s.c]=0;cells[s.r][s.c].textContent='';cells[s.r][s.c].className='';addBorders(s.r,s.c);cells[s.r][s.c].classList.add('anim-remove'); actionText.innerHTML='Backtracking at Row '+(s.r+1)+' Col '+(s.c+1);}\n"
"          else if(s.t===2){cells[s.r][s.c].className='';addBorders(s.r,s.c);cells[s.r][s.c].classList.add('anim-prune'); actionText.innerHTML='Pruning! Dead end at Row '+(s.r+1)+' Col '+(s.c+1);}\n"
"          animIdx++;\n"
"        }\n"
"        progFill.style.width=(animIdx/animSteps.length*100)+'%';\n"
"        if(animIdx>=animSteps.length){\n"
"          animating=false;animTitle.style.display='none';animCtrl.style.display='none';\n"
"          setButtonsEnabled(true); btnGen.disabled=false; btnBack.disabled=false;\n"
"          if(result.solved){\n"
"            for(let r=0;r<9;r++)for(let c=0;c<9;c++){puzzle[r][c]=result.grid[r][c];}\n"
"            renderGrid(puzzle,fixed);\n"
"          }\n"
"          showStats(label,result);return;\n"
"        }\n"
"        animTimer=requestAnimationFrame(tick);\n"
"      }\n"
"      animTimer=requestAnimationFrame(tick);\n"
"    }\n"
"\n"
"    function addBorders(r,c){\n"
"      const td=cells[r][c];\n"
"      if(c%3===2&&c<8)td.classList.add('thick-right');\n"
"      if(r%3===2&&r<8)td.classList.add('thick-bottom');\n"
"      if(c%3===0)td.classList.add('thick-left');\n"
"      if(r%3===0)td.classList.add('thick-top');\n"
"    }\n"
"\n"
"    function showStats(label,result){\n"
"      if(label==='bt')btStats=result;else bbStats=result;\n"
"      let h='<div class=\"stats-box\"><h3>Performance Comparison</h3>';\n"
"      if(btStats){\n"
"        h+='<div class=\"stat-row\"><span class=\"stat-label\">Backtracking Calls</span><span class=\"stat-val\">'+btStats.recursiveCalls+'</span></div>';\n"
"        h+='<div class=\"stat-row\"><span class=\"stat-label\">BT Time</span><span class=\"stat-val\">'+btStats.executionTimeMs.toFixed(3)+' ms</span></div>';\n"
"        h+='<div class=\"stat-row\"><span class=\"stat-label\">BT Steps</span><span class=\"stat-val\">'+btStats.stepCount+'</span></div>';\n"
"      }\n"
"      if(bbStats){\n"
"        h+='<div class=\"stat-row\"><span class=\"stat-label\">Branch&Bound Calls</span><span class=\"stat-val bb\">'+bbStats.recursiveCalls+'</span></div>';\n"
"        h+='<div class=\"stat-row\"><span class=\"stat-label\">B&B Time</span><span class=\"stat-val bb\">'+bbStats.executionTimeMs.toFixed(3)+' ms</span></div>';\n"
"        h+='<div class=\"stat-row\"><span class=\"stat-label\">B&B Steps</span><span class=\"stat-val bb\">'+bbStats.stepCount+'</span></div>';\n"
"      }\n"
"      if(btStats&&bbStats){\n"
"        const ratio=(btStats.recursiveCalls/bbStats.recursiveCalls).toFixed(1);\n"
"        h+='<div class=\"stat-row\" style=\"margin-top:8px;border-top:1px solid rgba(100,100,140,.3);padding-top:8px\">';\n"
"        h+='<span class=\"stat-label\">B&B Improvement</span><span class=\"stat-val ratio\">'+ratio+'x fewer calls!</span></div>';\n"
"      }\n"
"      h+='</div>';statsArea.innerHTML=h;\n"
"    }\n"
"\n"
"    btnBT.addEventListener('click',async()=>{\n"
"      if(!puzzle||animating)return;\n"
"      btnBT.disabled=true;btnBT.textContent='Solving...';\n"
"      try{\n"
"        if(!preSolveGrid){preSolveGrid=puzzle.map(r=>[...r]);}\n"
"        const res=await apiPost('/solve_bt',{grid:preSolveGrid});\n"
"        btnBT.textContent='Solve: Backtracking';\n"
"        runAnimation(res.steps,res,'bt');\n"
"      }catch(e){alert('Error: '+e.message);btnBT.disabled=false;btnBT.textContent='Solve: Backtracking';}\n"
"    });\n"
"\n"
"    btnBB.addEventListener('click',async()=>{\n"
"      if(!puzzle||animating)return;\n"
"      localStorage.removeItem('journey_steps');\n"
"      localStorage.removeItem('journey_puzzle');\n"
"      localStorage.removeItem('journey_result');\n"
"      const journeyWin=window.open('/journey','_blank');\n"
"      btnBB.disabled=true;btnBB.textContent='Solving...';\n"
"      try{\n"
"        if(!preSolveGrid){preSolveGrid=puzzle.map(r=>[...r]);}\n"
"        const res=await apiPost('/solve_bb',{grid:preSolveGrid});\n"
"        btnBB.textContent='Solve: Branch & Bound';\n"
"        localStorage.setItem('journey_steps',JSON.stringify(res.steps));\n"
"        localStorage.setItem('journey_puzzle',JSON.stringify(preSolveGrid));\n"
"        localStorage.setItem('journey_result',JSON.stringify({solved:res.solved,grid:res.grid,recursiveCalls:res.recursiveCalls,executionTimeMs:res.executionTimeMs,stepCount:res.stepCount}));\n"
"        runAnimation(res.steps,res,'bb');\n"
"      }catch(e){alert('Error: '+e.message);btnBB.disabled=false;btnBB.textContent='Solve: Branch & Bound';if(journeyWin)journeyWin.close();}\n"
"    });\n"
"\n"
"    buildGrid();\n"
"  </script>\n"
"</body>\n"
"</html>\n"
"\n"
"\n"
"\n"
"\n"
"\n";
