/* gui_html.c - Embedded HTML/CSS/JS frontend as a C string */
const char *GUI_HTML =
"<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Sudoku Solver - DAA Mini Project</title>"
"<link href='https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap' rel='stylesheet'>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:'Inter',sans-serif;background:#0d0d1a;color:#e0e0f0;min-height:100vh;"
"background-image:radial-gradient(ellipse at 20% 50%,rgba(60,40,120,.25) 0%,transparent 60%),"
"radial-gradient(ellipse at 80% 20%,rgba(30,80,120,.2) 0%,transparent 50%)}"
".container{max-width:1100px;margin:0 auto;padding:24px;display:flex;flex-wrap:wrap;gap:32px;justify-content:center}"
"h1{width:100%;text-align:center;font-size:2rem;font-weight:800;"
"background:linear-gradient(135deg,#a78bfa,#60a5fa,#34d399);-webkit-background-clip:text;"
"-webkit-text-fill-color:transparent;margin-bottom:0}"
".subtitle{width:100%;text-align:center;color:#8888aa;font-size:.85rem;margin-top:-12px;margin-bottom:4px}"
".grid-wrap{background:rgba(20,20,45,.7);border-radius:16px;padding:20px;"
"box-shadow:0 8px 32px rgba(0,0,0,.4),inset 0 1px 0 rgba(255,255,255,.05);backdrop-filter:blur(10px)}"
"table{border-collapse:collapse}"
"td{width:54px;height:54px;text-align:center;font-size:1.35rem;font-weight:600;"
"border:1px solid rgba(80,80,120,.4);cursor:pointer;position:relative;transition:background .15s}"
"td:hover{background:rgba(100,100,180,.15)}"
"td.fixed{color:#fff;font-weight:700}"
"td.user{color:#60d0f0}"
"td.error{color:#ff5555;background:rgba(255,0,0,.08)}"
"td.selected{background:rgba(100,120,220,.25)!important;box-shadow:inset 0 0 0 2px rgba(120,140,255,.5)}"
"td.hl-row-col{background:rgba(80,90,160,.1)}"
"td.anim-place{background:rgba(40,180,80,.3)!important;transition:background .08s}"
"td.anim-remove{background:rgba(200,50,50,.3)!important;transition:background .08s}"
"td.anim-prune{background:rgba(220,150,30,.3)!important;transition:background .08s}"
"td.hint-cell{background:rgba(255,215,0,.2)!important;animation:hintPulse 1s ease-in-out 3}"
"@keyframes hintPulse{0%,100%{box-shadow:inset 0 0 0 2px transparent}50%{box-shadow:inset 0 0 0 2px #ffd700}}"
"td.solved-anim{color:#34d399}"
".thick-right{border-right:2.5px solid rgba(130,130,200,.6)!important}"
".thick-bottom{border-bottom:2.5px solid rgba(130,130,200,.6)!important}"
".thick-left{border-left:2.5px solid rgba(130,130,200,.6)!important}"
".thick-top{border-top:2.5px solid rgba(130,130,200,.6)!important}"
".panel{display:flex;flex-direction:column;gap:12px;min-width:280px}"
".btn{padding:12px 20px;border:none;border-radius:10px;font-family:'Inter',sans-serif;"
"font-size:.9rem;font-weight:600;cursor:pointer;transition:all .2s;"
"background:linear-gradient(135deg,#4c3b99,#5b4abf);color:#fff;"
"box-shadow:0 4px 15px rgba(80,60,180,.3)}"
".btn:hover{transform:translateY(-1px);box-shadow:0 6px 20px rgba(80,60,180,.5);"
"background:linear-gradient(135deg,#5b4abf,#6d5dd3)}"
".btn:active{transform:translateY(0)}"
".btn:disabled{opacity:.4;cursor:not-allowed;transform:none}"
".btn.secondary{background:linear-gradient(135deg,#2a2a4a,#3a3a5a);box-shadow:0 4px 15px rgba(0,0,0,.3)}"
".btn.secondary:hover{background:linear-gradient(135deg,#3a3a5a,#4a4a6a)}"
".section-title{font-size:.75rem;font-weight:700;color:#8888aa;text-transform:uppercase;letter-spacing:1.5px;margin-top:8px}"
".radio-group{display:flex;flex-direction:column;gap:6px}"
".radio-group label{display:flex;align-items:center;gap:8px;cursor:pointer;font-size:.85rem;color:#c0c0e0;"
"padding:6px 10px;border-radius:8px;transition:background .15s}"
".radio-group label:hover{background:rgba(100,100,180,.1)}"
".radio-group input[type=radio]{appearance:none;width:16px;height:16px;border:2px solid #6666aa;"
"border-radius:50%;position:relative;cursor:pointer;transition:all .15s}"
".radio-group input[type=radio]:checked{border-color:#60a5fa;background:transparent}"
".radio-group input[type=radio]:checked::after{content:'';position:absolute;top:3px;left:3px;"
"width:6px;height:6px;background:#60a5fa;border-radius:50%}"
".stats-box{background:rgba(20,22,45,.6);border-radius:12px;padding:14px;border:1px solid rgba(80,80,120,.2)}"
".stats-box h3{font-size:.8rem;color:#aaa;margin-bottom:8px;font-weight:600}"
".stat-row{display:flex;justify-content:space-between;font-size:.8rem;padding:3px 0}"
".stat-label{color:#9999bb}.stat-val{color:#34d399;font-weight:600}"
".stat-val.bb{color:#fbbf24}"
".stat-val.ratio{color:#f472b6;font-size:.9rem;font-weight:700}"
".legend{display:flex;gap:16px;flex-wrap:wrap;margin-top:8px}"
".legend-item{display:flex;align-items:center;gap:5px;font-size:.72rem;color:#9999aa}"
".legend-color{width:14px;height:14px;border-radius:3px}"
".anim-controls{font-size:.8rem;color:#9999bb}"
".anim-controls span{color:#c0c0e0}"
".speed-display{font-size:.85rem;color:#60a5fa;font-weight:600}"
".progress-bar{width:100%;height:4px;background:rgba(60,60,100,.4);border-radius:2px;overflow:hidden;margin-top:4px}"
".progress-fill{height:100%;background:linear-gradient(90deg,#60a5fa,#34d399);border-radius:2px;transition:width .1s}"
"input.cell-input{position:absolute;top:0;left:0;width:100%;height:100%;border:none;background:transparent;"
"text-align:center;font-size:1.35rem;font-weight:600;color:#60d0f0;font-family:'Inter',sans-serif;"
"outline:none;caret-color:#60a5fa}"
"</style></head><body>"
"<div class='container'>"
"<h1>SUDOKU SOLVER</h1>"
"<p class='subtitle'>Backtracking & Branch and Bound &mdash; Design & Analysis of Algorithms Mini Project</p>"
"<div class='grid-wrap'>"
"<table id='grid'></table>"
"<div class='legend'>"
"<div class='legend-item'><div class='legend-color' style='background:rgba(40,180,80,.5)'></div>Placing</div>"
"<div class='legend-item'><div class='legend-color' style='background:rgba(200,50,50,.5)'></div>Backtrack</div>"
"<div class='legend-item'><div class='legend-color' style='background:rgba(220,150,30,.5)'></div>Pruned</div>"
"<div class='legend-item'><div class='legend-color' style='background:rgba(255,215,0,.3)'></div>Hint</div>"
"</div></div>"
"<div class='panel'>"
"<button class='btn' id='btnGen'>Generate Puzzle</button>"
"<button class='btn' id='btnBT' disabled>Solve: Backtracking</button>"
"<button class='btn' id='btnBB' disabled>Solve: Branch & Bound</button>"
"<button class='btn secondary' id='btnReset' disabled>Reset Puzzle</button>"
"<button class='btn secondary' id='btnHint' disabled>Hint</button>"
"<div class='section-title'>Difficulty</div>"
"<div class='radio-group'>"
"<label><input type='radio' name='diff' value='0' checked>Easy (30 blanks)</label>"
"<label><input type='radio' name='diff' value='1'>Medium (40 blanks)</label>"
"<label><input type='radio' name='diff' value='2'>Hard (50 blanks)</label>"
"</div>"
"<div class='section-title' id='animTitle' style='display:none'>Animation</div>"
"<div class='anim-controls' id='animCtrl' style='display:none'>"
"<div class='speed-display' id='speedDisp'></div>"
"<div class='progress-bar'><div class='progress-fill' id='progFill'></div></div>"
"<div style='margin-top:6px'><span>[+/-]</span> Speed &nbsp; <span>[Space]</span> Pause</div></div>"
"<div id='statsArea'></div>"
"</div></div>"
"<script>"
"const grid=document.getElementById('grid');"
"const btnGen=document.getElementById('btnGen');"
"const btnBT=document.getElementById('btnBT');"
"const btnBB=document.getElementById('btnBB');"
"const btnReset=document.getElementById('btnReset');"
"const btnHint=document.getElementById('btnHint');"
"const animTitle=document.getElementById('animTitle');"
"const animCtrl=document.getElementById('animCtrl');"
"const speedDisp=document.getElementById('speedDisp');"
"const progFill=document.getElementById('progFill');"
"const statsArea=document.getElementById('statsArea');"
"let cells=[],puzzle=null,fixed=null,solution=null,selR=-1,selC=-1;"
"let animating=false,animPaused=false,animSpeed=150,animSteps=[],animIdx=0,animTimer=null;"
"let btStats=null,bbStats=null,dispGrid=null;"
""
"function buildGrid(){"
"  grid.innerHTML='';"
"  cells=[];"
"  for(let r=0;r<9;r++){"
"    const tr=document.createElement('tr');"
"    cells[r]=[];"
"    for(let c=0;c<9;c++){"
"      const td=document.createElement('td');"
"      if(c%3===2&&c<8)td.classList.add('thick-right');"
"      if(r%3===2&&r<8)td.classList.add('thick-bottom');"
"      if(c%3===0)td.classList.add('thick-left');"
"      if(r%3===0)td.classList.add('thick-top');"
"      td.dataset.r=r;td.dataset.c=c;"
"      td.addEventListener('click',()=>selectCell(r,c));"
"      tr.appendChild(td);"
"      cells[r][c]=td;"
"    }"
"    grid.appendChild(tr);"
"  }"
"}"
""
"function renderGrid(g,f){"
"  for(let r=0;r<9;r++)for(let c=0;c<9;c++){"
"    const td=cells[r][c];"
"    td.textContent=g[r][c]||'';"
"    td.className='';"
"    if(c%3===2&&c<8)td.classList.add('thick-right');"
"    if(r%3===2&&r<8)td.classList.add('thick-bottom');"
"    if(c%3===0)td.classList.add('thick-left');"
"    if(r%3===0)td.classList.add('thick-top');"
"    if(f&&f[r][c])td.classList.add('fixed');"
"    else if(g[r][c])td.classList.add('user');"
"  }"
"}"
""
"function selectCell(r,c){"
"  if(animating)return;"
"  document.querySelectorAll('td.selected,td.hl-row-col').forEach(e=>{"
"    e.classList.remove('selected','hl-row-col');"
"  });"
"  selR=r;selC=c;"
"  cells[r][c].classList.add('selected');"
"  for(let i=0;i<9;i++){cells[r][i].classList.add('hl-row-col');cells[i][c].classList.add('hl-row-col');}"
"  cells[r][c].classList.remove('hl-row-col');"
"  cells[r][c].classList.add('selected');"
"}"
""
"function validateGrid(){"
"  if(!puzzle)return;"
"  for(let r=0;r<9;r++)for(let c=0;c<9;c++){"
"    cells[r][c].classList.remove('error');"
"    const v=puzzle[r][c];"
"    if(v&&!fixed[r][c]){"
"      let err=false;"
"      for(let i=0;i<9;i++){if(i!==c&&puzzle[r][i]===v)err=true;if(i!==r&&puzzle[i][c]===v)err=true;}"
"      const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;"
"      for(let dr=0;dr<3;dr++)for(let dc=0;dc<3;dc++){"
"        if(br+dr!==r||bc+dc!==c){if(puzzle[br+dr][bc+dc]===v)err=true;}"
"      }"
"      if(err)cells[r][c].classList.add('error');"
"    }"
"  }"
"}"
""
"document.addEventListener('keydown',e=>{"
"  if(animating){"
"    if(e.key==='='||e.key==='+'){animSpeed=Math.min(animSpeed*1.5,8000);speedDisp.textContent='Speed: '+Math.round(animSpeed)+' steps/sec';}"
"    if(e.key==='-'){animSpeed=Math.max(animSpeed/1.5,5);speedDisp.textContent='Speed: '+Math.round(animSpeed)+' steps/sec';}"
"    if(e.key===' '){animPaused=!animPaused;e.preventDefault();}"
"    return;"
"  }"
"  if(selR<0||!puzzle||fixed[selR][selC])return;"
"  if(e.key>='1'&&e.key<='9'){puzzle[selR][selC]=parseInt(e.key);renderGrid(puzzle,fixed);selectCell(selR,selC);validateGrid();}"
"  if(e.key==='Backspace'||e.key==='Delete'||e.key==='0'){puzzle[selR][selC]=0;renderGrid(puzzle,fixed);selectCell(selR,selC);validateGrid();}"
"  if(e.key==='ArrowUp'&&selR>0){selectCell(selR-1,selC);}"
"  if(e.key==='ArrowDown'&&selR<8){selectCell(selR+1,selC);}"
"  if(e.key==='ArrowLeft'&&selC>0){selectCell(selR,selC-1);}"
"  if(e.key==='ArrowRight'&&selC<8){selectCell(selR,selC+1);}"
"});"
""
"async function apiPost(url,data){"
"  const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});"
"  return r.json();"
"}"
""
"btnGen.addEventListener('click',async()=>{"
"  const diff=parseInt(document.querySelector('input[name=diff]:checked').value);"
"  btnGen.disabled=true;btnGen.textContent='Generating...';"
"  try{"
"    const d=await apiPost('/generate',{difficulty:diff});"
"    puzzle=d.grid;fixed=d.fixed;solution=d.solution;"
"    renderGrid(puzzle,fixed);"
"    btnBT.disabled=false;btnBB.disabled=false;btnReset.disabled=false;btnHint.disabled=false;"
"    btStats=null;bbStats=null;statsArea.innerHTML='';"
"  }catch(e){alert('Error: '+e.message);}"
"  btnGen.disabled=false;btnGen.textContent='Generate Puzzle';"
"});"
""
"btnReset.addEventListener('click',()=>{"
"  if(!solution)return;"
"  for(let r=0;r<9;r++)for(let c=0;c<9;c++){if(!fixed[r][c])puzzle[r][c]=0;}"
"  renderGrid(puzzle,fixed);validateGrid();"
"  btStats=null;bbStats=null;statsArea.innerHTML='';"
"});"
""
"btnHint.addEventListener('click',async()=>{"
"  if(!puzzle)return;"
"  try{"
"    const d=await apiPost('/hint',{grid:puzzle});"
"    if(d.found){"
"      puzzle[d.row][d.col]=d.value;renderGrid(puzzle,fixed);"
"      cells[d.row][d.col].classList.add('hint-cell');"
"      setTimeout(()=>cells[d.row][d.col].classList.remove('hint-cell'),3000);"
"      validateGrid();"
"    }"
"  }catch(e){}"
"});"
""
"function setButtonsEnabled(en){"
"  btnGen.disabled=!en;btnBT.disabled=!en;btnBB.disabled=!en;btnReset.disabled=!en;btnHint.disabled=!en;"
"}"
""
"function runAnimation(steps,result,label){"
"  animating=true;animPaused=false;animSteps=steps;animIdx=0;"
"  dispGrid=puzzle.map(r=>[...r]);"
"  setButtonsEnabled(false);"
"  animTitle.style.display='block';animCtrl.style.display='block';"
"  speedDisp.textContent='Speed: '+Math.round(animSpeed)+' steps/sec';"
""
"  function tick(){"
"    if(!animating)return;"
"    if(animPaused){animTimer=requestAnimationFrame(tick);return;}"
"    const stepsPerFrame=Math.max(1,Math.round(animSpeed/60));"
"    for(let i=0;i<stepsPerFrame&&animIdx<animSteps.length;i++){"
"      const s=animSteps[animIdx];"
"      document.querySelectorAll('td.anim-place,td.anim-remove,td.anim-prune').forEach(e=>{"
"        e.classList.remove('anim-place','anim-remove','anim-prune');"
"      });"
"      if(s.t===0){dispGrid[s.r][s.c]=s.v;cells[s.r][s.c].textContent=s.v||'';cells[s.r][s.c].className='';addBorders(s.r,s.c);cells[s.r][s.c].classList.add('solved-anim','anim-place');}"
"      else if(s.t===1){dispGrid[s.r][s.c]=0;cells[s.r][s.c].textContent='';cells[s.r][s.c].className='';addBorders(s.r,s.c);cells[s.r][s.c].classList.add('anim-remove');}"
"      else if(s.t===2){cells[s.r][s.c].className='';addBorders(s.r,s.c);cells[s.r][s.c].classList.add('anim-prune');}"
"      animIdx++;"
"    }"
"    progFill.style.width=(animIdx/animSteps.length*100)+'%';"
"    if(animIdx>=animSteps.length){"
"      animating=false;animTitle.style.display='none';animCtrl.style.display='none';"
"      setButtonsEnabled(true);"
"      if(result.solved){"
"        for(let r=0;r<9;r++)for(let c=0;c<9;c++){puzzle[r][c]=result.grid[r][c];}"
"        renderGrid(puzzle,fixed);"
"      }"
"      showStats(label,result);return;"
"    }"
"    animTimer=requestAnimationFrame(tick);"
"  }"
"  animTimer=requestAnimationFrame(tick);"
"}"
""
"function addBorders(r,c){"
"  const td=cells[r][c];"
"  if(c%3===2&&c<8)td.classList.add('thick-right');"
"  if(r%3===2&&r<8)td.classList.add('thick-bottom');"
"  if(c%3===0)td.classList.add('thick-left');"
"  if(r%3===0)td.classList.add('thick-top');"
"}"
""
"function showStats(label,result){"
"  if(label==='bt')btStats=result;else bbStats=result;"
"  let h='<div class=\"stats-box\"><h3>Performance Comparison</h3>';"
"  if(btStats){"
"    h+='<div class=\"stat-row\"><span class=\"stat-label\">Backtracking Calls</span><span class=\"stat-val\">'+btStats.recursiveCalls+'</span></div>';"
"    h+='<div class=\"stat-row\"><span class=\"stat-label\">BT Time</span><span class=\"stat-val\">'+btStats.executionTimeMs.toFixed(3)+' ms</span></div>';"
"    h+='<div class=\"stat-row\"><span class=\"stat-label\">BT Steps</span><span class=\"stat-val\">'+btStats.stepCount+'</span></div>';"
"  }"
"  if(bbStats){"
"    h+='<div class=\"stat-row\"><span class=\"stat-label\">Branch&Bound Calls</span><span class=\"stat-val bb\">'+bbStats.recursiveCalls+'</span></div>';"
"    h+='<div class=\"stat-row\"><span class=\"stat-label\">B&B Time</span><span class=\"stat-val bb\">'+bbStats.executionTimeMs.toFixed(3)+' ms</span></div>';"
"    h+='<div class=\"stat-row\"><span class=\"stat-label\">B&B Steps</span><span class=\"stat-val bb\">'+bbStats.stepCount+'</span></div>';"
"  }"
"  if(btStats&&bbStats){"
"    const ratio=(btStats.recursiveCalls/bbStats.recursiveCalls).toFixed(1);"
"    h+='<div class=\"stat-row\" style=\"margin-top:8px;border-top:1px solid rgba(100,100,140,.3);padding-top:8px\">';"
"    h+='<span class=\"stat-label\">B&B Improvement</span><span class=\"stat-val ratio\">'+ratio+'x fewer calls!</span></div>';"
"  }"
"  h+='</div>';statsArea.innerHTML=h;"
"}"
""
"btnBT.addEventListener('click',async()=>{"
"  if(!puzzle||animating)return;"
"  btnBT.disabled=true;btnBT.textContent='Solving...';"
"  try{"
"    const res=await apiPost('/solve_bt',{grid:puzzle});"
"    btnBT.textContent='Solve: Backtracking';"
"    runAnimation(res.steps,res,'bt');"
"  }catch(e){alert('Error: '+e.message);btnBT.disabled=false;btnBT.textContent='Solve: Backtracking';}"
"});"
""
"btnBB.addEventListener('click',async()=>{"
"  if(!puzzle||animating)return;"
"  btnBB.disabled=true;btnBB.textContent='Solving...';"
"  try{"
"    const res=await apiPost('/solve_bb',{grid:puzzle});"
"    btnBB.textContent='Solve: Branch & Bound';"
"    runAnimation(res.steps,res,'bb');"
"  }catch(e){alert('Error: '+e.message);btnBB.disabled=false;btnBB.textContent='Solve: Branch & Bound';}"
"});"
""
"buildGrid();"
"</script></body></html>"
;
